CREATE TABLE tokens (
  id SERIAL PRIMARY KEY, 
  user_id INTEGER, 
  name VARCHAR (255), 
  email VARCHAR (255) NOT NULL,
  token_hash BYTEA VARYING (255),
  expiry TIMESTAMP
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE tokens ADD COLUMN created_at TIMESTAMP DEFAULT NOW();